#!/usr/bin/env bash
# Install, upgrade, or uninstall server-status. Self-contained: works from a
# git checkout, from a bare downloaded binary, or with no local files at all.
#
# Usage:
#   sudo ./install.sh                 install/upgrade, prompting for config on first install
#   sudo ./install.sh --non-interactive   skip prompts, write a placeholder config to edit by hand
#   sudo ./install.sh --uninstall     stop the service, purge HA discovery, remove the unit
#
# One-liner (no clone, no manual download):
#   curl -fsSL https://raw.githubusercontent.com/giovi321/server-status-go/main/scripts/install.sh | sudo bash
#
# Binary resolution order:
#   1. $SRC_BIN, if set
#   2. ./server-status
#   3. ./server-status-linux-<arch>   (the release asset, as downloaded, no rename needed)
#   4. downloaded from the $REPO release tagged $VERSION (default: latest), checksum-verified
#
# On first install (no existing config.yaml) it prompts, over /dev/tty so this
# works even when piped through curl, for the node name and MQTT broker
# details. Any answer can be preset via env var (NODE_NAME, MQTT_HOST,
# MQTT_PORT, MQTT_USERNAME, MQTT_PASSWORD) to skip that prompt.
set -euo pipefail

REPO=${REPO:-giovi321/server-status-go}
VERSION=${VERSION:-latest}
BIN_DIR=/opt/server-status
CFG_DIR=/etc/server-status
UNIT=/etc/systemd/system/server-status.service
NON_INTERACTIVE=0
[[ "${1:-}" == "--non-interactive" ]] && NON_INTERACTIVE=1

if [[ "${1:-}" == "--uninstall" ]]; then
  systemctl disable --now server-status.service 2>/dev/null || true
  if [[ -x "$BIN_DIR/server-status" && -f "$CFG_DIR/config.yaml" ]]; then
    if [[ -f "$CFG_DIR/server-status.env" ]]; then set -a; . "$CFG_DIR/server-status.env"; set +a; fi
    "$BIN_DIR/server-status" -c "$CFG_DIR/config.yaml" --purge 2>/dev/null || true
  fi
  rm -f "$UNIT"
  systemctl daemon-reload
  echo "Uninstalled service and cleared Home Assistant discovery. Left $CFG_DIR and $BIN_DIR in place."
  exit 0
fi

case "$(uname -m)" in
  x86_64) ARCH=amd64 ;;
  aarch64|arm64) ARCH=arm64 ;;
  *) echo "unsupported architecture: $(uname -m)" >&2; exit 1 ;;
esac
ASSET="server-status-linux-$ARCH"

resolve_binary() {
  if [[ -n "${SRC_BIN:-}" ]]; then
    [[ -f "$SRC_BIN" ]] || { echo "SRC_BIN=$SRC_BIN not found" >&2; exit 1; }
    printf '%s\n' "$SRC_BIN"
    return
  fi
  if [[ -f "./server-status" ]]; then printf '%s\n' "./server-status"; return; fi
  if [[ -f "./$ASSET" ]]; then printf '%s\n' "./$ASSET"; return; fi

  command -v curl >/dev/null || { echo "no local binary found and curl is missing to download one; install curl or set SRC_BIN" >&2; exit 1; }
  local base tmpdir
  if [[ "$VERSION" == "latest" ]]; then
    base="https://github.com/$REPO/releases/latest/download"
  else
    base="https://github.com/$REPO/releases/download/$VERSION"
  fi
  tmpdir=$(mktemp -d)
  echo "no local binary found; downloading $ASSET ($VERSION) from $REPO" >&2
  curl -fL -o "$tmpdir/$ASSET" "$base/$ASSET"
  curl -fL -o "$tmpdir/$ASSET.sha256" "$base/$ASSET.sha256"
  ( cd "$tmpdir" && sha256sum -c "$ASSET.sha256" ) >&2
  chmod +x "$tmpdir/$ASSET"
  printf '%s\n' "$tmpdir/$ASSET"
}

SRC=$(resolve_binary)

install -d "$BIN_DIR" "$CFG_DIR"
install -m 0755 "$SRC" "$BIN_DIR/server-status"

# Reads one line from the controlling terminal, not stdin, so prompts still
# work when this script itself arrived via `curl | sudo bash`.
ask() {
  local question=$1 default=${2:-} ans
  read -r -p "$question" ans </dev/tty || ans=""
  printf '%s\n' "${ans:-$default}"
}

ask_secret() {
  local question=$1 ans
  read -rs -p "$question" ans </dev/tty || ans=""
  echo >&2
  printf '%s\n' "$ans"
}

if [[ ! -f "$CFG_DIR/config.yaml" ]]; then
  node_name=${NODE_NAME:-$(hostname)}
  mqtt_host=${MQTT_HOST:-}
  mqtt_port=${MQTT_PORT:-1883}
  mqtt_user=${MQTT_USERNAME:-mqtt}
  mqtt_pass=${MQTT_PASSWORD:-}

  if [[ "$NON_INTERACTIVE" -eq 0 && -r /dev/tty ]]; then
    echo "Configuring server-status. Press enter to accept a default in [brackets]." >&2
    [[ -z "${NODE_NAME:-}" ]] && node_name=$(ask "Node name [$node_name]: " "$node_name")
    while [[ -z "$mqtt_host" ]]; do
      mqtt_host=$(ask "MQTT broker host or IP: " "")
      [[ -z "$mqtt_host" ]] && echo "a broker host is required" >&2
    done
    [[ -z "${MQTT_PORT:-}" ]] && mqtt_port=$(ask "MQTT broker port [$mqtt_port]: " "$mqtt_port")
    [[ -z "${MQTT_USERNAME:-}" ]] && mqtt_user=$(ask "MQTT username [$mqtt_user]: " "$mqtt_user")
    [[ -z "$mqtt_pass" ]] && mqtt_pass=$(ask_secret "MQTT password: ")
  elif [[ -z "$mqtt_host" ]]; then
    echo "No terminal to prompt on and no MQTT_HOST set; writing a placeholder config -" \
         "edit $CFG_DIR/config.yaml and $CFG_DIR/server-status.env by hand." >&2
    mqtt_host="192.168.1.65"
  fi

  {
    printf '%s\n' "# Generated by install.sh. See docs for the full configuration reference."
    printf 'node: %s\n' "$node_name"
    printf 'sinks:\n'
    printf '  - type: mqtt\n'
    printf '    host: %s\n' "$mqtt_host"
    printf '    port: %s\n' "$mqtt_port"
    printf '    username: %s\n' "$mqtt_user"
    printf '    password: ${MQTT_PASSWORD}\n'
  } > "$CFG_DIR/config.yaml"
  echo "Wrote config to $CFG_DIR/config.yaml."
fi

if [[ ! -f "$CFG_DIR/server-status.env" ]]; then
  {
    printf '%s\n' "# Secrets for server-status, loaded into the service environment by systemd"
    printf '%s\n' "# (EnvironmentFile in the unit). Referenced from config.yaml as \${MQTT_PASSWORD}."
    printf 'MQTT_PASSWORD=%s\n' "${mqtt_pass:-}"
  } > "$CFG_DIR/server-status.env"
  chmod 600 "$CFG_DIR/server-status.env"
  if [[ -n "${mqtt_pass:-}" ]]; then
    echo "Wrote $CFG_DIR/server-status.env with the MQTT password (chmod 600)."
  else
    echo "Wrote secret stub to $CFG_DIR/server-status.env (set MQTT_PASSWORD there; it is chmod 600)."
  fi
fi

# Kept identical to packaging/server-status.service so the script has no other file dependency.
cat > "$UNIT" <<'UNITEOF'
[Unit]
Description=server-status metrics publisher
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
WatchdogSec=180
User=root
EnvironmentFile=-/etc/server-status/server-status.env
ExecStart=/opt/server-status/server-status -c /etc/server-status/config.yaml
Restart=always
RestartSec=15s
TimeoutStopSec=10s
# Sandboxing that does not block hardware access; expanded in a later reliability plan.
ProtectHome=true
NoNewPrivileges=false

[Install]
WantedBy=multi-user.target
UNITEOF
chmod 0644 "$UNIT"

systemctl daemon-reload
systemctl enable server-status.service
systemctl restart server-status.service
echo "Installed server-status. Set MQTT_PASSWORD in $CFG_DIR/server-status.env, then: systemctl restart server-status. Logs: journalctl -u server-status -f"
